CREATE VIEW TopDoctor
AS  SELECT F_Name, L_Name, Start_Date
    FROM CLASS1_PATIENT, CLASS2_PATIENT, EMPLOYEE, PERSON
    WHERE EMPLOYEE.Person_ID=PERSON.Person_ID AND
    	  5<ALL (SELECT COUNT(Doctor_ID) FROM CLASS1_PATIENT WHERE Doctor_ID=EMPLOYEE.Person_ID) AND
    	  10<ALL (SELECT COUNT(Doctor_ID) FROM CLASS2_PATIENT WHERE Doctor_ID=EMPLOYEE.Person_ID);


CREATE VIEW TopTreatment
AS  SELECT Name, Price
	FROM ASSIGNED, TREATMENT, MEDICINE
	WHERE TREATMENT.Treatment_ID=ASSIGNED.Treatment_ID AND
		  ASSIGNED.Medicine_Code=MEDICINE.Medicine_Code
	GROUP BY Treatment_ID
	ORDER BY COUNT(Treatment_ID) DESC
	LIMIT 1;


CREATE VIEW ReorderMeds
AS  SELECT *
	FROM MEDICINE
	WHERE Quantity < 1000 AND 
	DATE_ADD(CURDATE(), INTERVAL 31 DAY)<Date_Of_Expiration;


CREATE VIEW PotentialPatient
AS  SELECT F_Name, M_Name, L_Name, Phone_Number, 
		PERSON.Person_ID AS Person_ID
	FROM PERSON, CLASS1_PATIENT
	WHERE PERSON.Person_ID=CLASS1_PATIENT.Person_ID
	GROUP BY CLASS1_PATIENT.Person_ID
	HAVING Count(CLASS1_PATIENT.Person_ID) > 3;


CREATE VIEW MostFrequentIssues
AS  SELECT Treatment_ID, Name, COUNT(Treatment_ID) AS Frequency
	FROM ASSIGNED, TREATMENT
	WHERE TREATMENT.Treatment_ID=ASSIGNED.Treatment_ID
	GROUP BY Treatment_ID
	ORDER BY COUNT(Treatment_ID) DESC;