USE hospital ;
GO

CREATE VIEW TopDoctor
AS  SELECT F_Name, L_Name, Start_Date
    FROM CLASS1_PATIENT, CLASS2_PATIENT, EMPLOYEE, PERSON
    WHERE EMPLOYEE.Person_ID=PERSON.Person_ID 
	GROUP BY EMPLOYEE.Person_ID, CLASS1_PATIENT.Doctor_ID, F_Name, L_Name, Start_Date
	HAVING
    	  5<ALL (SELECT COUNT(Doctor_ID) FROM CLASS1_PATIENT WHERE Doctor_ID=EMPLOYEE.Person_ID) AND
    	  10<ALL (SELECT COUNT(Doctor_ID) FROM CLASS2_PATIENT WHERE Doctor_ID=EMPLOYEE.Person_ID);