USE hospital ;
GO

CREATE VIEW TopTreatment
AS  SELECT TOP 1 MEDICINE.Name, Price
	FROM ASSIGNED, TREATMENT, MEDICINE
	WHERE TREATMENT.Treatment_ID=ASSIGNED.Treatment_ID AND
		  ASSIGNED.Medicine_Code=MEDICINE.Medicine_Code
	GROUP BY TREATMENT.Treatment_ID
	ORDER BY COUNT(TREATMENT.Treatment_ID) DESC;